# Master metrics
master.source.jvm.class=org.apache.spark.metrics.source.JvmSource
*.sink.prometheusServlet.class=org.apache.spark.metrics.sink.PrometheusServlet
*.sink.prometheusServlet.path=/metrics/prometheus

# Worker metrics
worker.source.jvm.class=org.apache.spark.metrics.source.JvmSource
